### PR TITLE
feat: add Simplified Chinese

### PR DESCRIPTION
**Pull request by theetrain**
Technically this file should be named `zh-Hans.json` for Simplified Chinese, but the array returned from `languages` strips out the locale suffix and I couldn't get it to load.

### CODE REVIEW

**Comment by jasonlyu123** [comment]
I was about to add traditional Chinese and encountered the same problem. I have yet to figure out if there is any config for achieving this. But we could override `zh-TW`, `zh-HK` and `zh-MO` to `zh-Hant` with some custom code and leave `zh` as simplified. Do we want to have Traditional Chinese as well? And if so, do we want to make it simple and require manual switching, or add some custom code to override it?

**Comment by jasonlyu123** [comment]
They use [navigator.languages](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/languages) to detect. For me, it's `zh-TW`, `zh`, `en-US` and `en`. So, It probably only has regional codes in it.  It'll work if it's `zh-TW`, but then we'll have to repeat the same file/links multiple times. Probably makes sense to just manually map those three to `zh-Hant` and the rest go to `zh` which is simplified.

**Comment by theetrain** [comment]
> Having both traditional and simplified would be great, the button label being the language tag would make them stand out a bit though.

Agreed to both. If you like, I can modify every language JSON to include a `language` key with their display language as the value, such as:

```json
{
	"in-memoriam": "Anh sẽ mãi được yêu mến và ghi nhớ trong trái tim mọi người",
	"language": "Tiếng Việt"
}
```

> I tested replacing en.json with en-GB.json and en-US.json and that worked. So maybe it only picks up variations of more than one is defined?

I tried this as well, but it doesn't render any text. Did I miss something? The value of `language` from `@inlang/sdk-js` for me is `en`, but my browser console output of `navigator.language` is `en-CA`.

image

**Comment by dominikg** [comment]
i'll go ahead and merge this PR. 

To support variants, languages would need to be listed here explicitly
https://github.com/dominikg/flyhighivan/blob/2e68ec5a3a91bc78904f24cfbc80734af93ebab9/inlang.config.js#L17

```js
referenceLanguage: 'de',
languages:['ar','ca','de','en','es','fr','hi','id','it','ja','pt','sv','ua','vi','zh-Hans'],
```

and then the language picker improvements mentioned above. Both can be done in a separate PR

**Pull request merged**
